apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-vela-extensions
  namespace: vela-system
  labels:
    fluxcd.io/system: bootstrap
spec:
  chart:
    spec:
      chart: flux-vela-extensions
      interval: 5m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: vela-system
      version: 1.0.0
  install:
    createNamespace: false
    disableHooks: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: flux-vela-extensions
  targetNamespace: vela-system
  timeout: 15m
  upgrade:
    disableHooks: false
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: flux-vela-extensions-values
