apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux2
  namespace: vela-system
  labels:
    fluxcd.io/system: bootstrap
spec:
  chart:
    spec:
      chart: flux2
      interval: 5m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: vela-system
      version: 2.9.2
  dependsOn:
    - name: vela-core
      namespace: vela-system
  install:
    createNamespace: false
    disableHooks: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: flux2
  targetNamespace: vela-system
  timeout: 15m
  upgrade:
    disableHooks: false
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: flux2-values
