apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-monitoring-values
  namespace: vela-system
data:
  values.yaml: |
    env: kind-flux
    loki-stack:
      promtail:
        namespace: monitoring
        enabled: true
      loki:
        enabled: true
        isDefault: false
        serviceMonitor:
          enabled: true
          additionalLabels:
            app.kubernetes.io/part-of: kube-prometheus-stack
        config:
          chunk_store_config:
            max_look_back_period: 0s
          table_manager:
            retention_deletes_enabled: true
            retention_period: 12h
    
    kube-prometheus-stack:
      namespaceOverride: monitoring
      alertmanager:
        enabled: false
      prometheus:
        enabled: false
        prometheusSpec:
          retention: 24h
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          podMonitorNamespaceSelector: { }
          podMonitorSelector:
            matchLabels:
              app.kubernetes.io/component: monitoring
      grafana:
        defaultDashboardsEnabled: false
        adminPassword: flux
