apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: init-apps
  namespace: vela-system
spec:
  interval: 1m
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: vela-apps
    namespace: flux-bootstrap
  path: ./init-apps
